spring:
  profiles:
    active: dev
  application:
    name: ProjetoNPJ
  data:
    mongodb:
      uri: mongodb://localhost:27017/ProjetoNPJ
jwt:
  secret: JvrdrGOKDYhaEyHycTLSM2dpR+dxTk1MbPy6o6e6M1dmc3PFbiJYTVqYIl0siuNoxzLXw7HwgnVzVNAt/xaTpQ==
  accessTokenExpiration: 180000  # 180000 = 3 minutos;  3600000 = 1 hora em milissegundos
  refreshTokenExpiration: 300000  # 604800000 = 7 dias; 28800000 = 8 horas em milissegundos   300000 = 5 minutos

logging:
  level:
    root: INFO # Nível padrão para todos os pacotes
    com.npj.ProjetoNPJ: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

    